# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 18:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170702_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to='', verbose_name=django.core.validators.FileExtensionValidator(allowed_extensions=['bufr', 'jpf', 'png', 'emf', 'fits', 'j2k', 'jfif', 'gif', 'gbr', 'ftc', 'pbm', 'ico', 'jpx', 'jpeg', 'pcd', 'iim', 'msp', 'hdf', 'tga', 'bmp', 'tiff', 'mic', 'psd', 'jpe', 'dcx', 'xpm', 'h5', 'mpg', 'mpeg', 'palm', 'mpo', 'fli', 'rgba', 'jpc', 'fpx', 'j2c', 'jpg', 'im', 'wmf', 'ps', 'jp2', 'sgi', 'icns', 'flc', 'fit', 'ftu', 'pdf', 'bw', 'tif', 'ras', 'eps', 'rgb', 'xbm', 'dds', 'cur', 'ppm', 'pcx', 'pgm', 'grib'])),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='', verbose_name=django.core.validators.FileExtensionValidator(allowed_extensions='mp3')),
        ),
    ]
