# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 18:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20170702_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to='', verbose_name=django.core.validators.FileExtensionValidator(allowed_extensions=['pgm', 'mic', 'ico', 'icns', 'jpx', 'j2c', 'bmp', 'jpg', 'fpx', 'fli', 'jpf', 'ppm', 'xbm', 'tga', 'ftc', 'wmf', 'pbm', 'im', 'jpc', 'mpeg', 'xpm', 'ps', 'palm', 'tiff', 'png', 'pcx', 'rgba', 'rgb', 'fits', 'ras', 'grib', 'pcd', 'gif', 'sgi', 'mpg', 'dds', 'j2k', 'dcx', 'hdf', 'bufr', 'bw', 'h5', 'fit', 'jpe', 'msp', 'jfif', 'eps', 'flc', 'psd', 'pdf', 'emf', 'iim', 'mpo', 'ftu', 'tif', 'jp2', 'gbr', 'cur', 'jpeg'])),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='', verbose_name=django.core.validators.FileExtensionValidator(allowed_extensions=('mp3', 'mp4'))),
        ),
    ]
