# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20170702_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_fav',
            new_name='is_favorite',
        ),
        migrations.AddField(
            model_name='album',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
