# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20170708_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, default='static/Screenshot_43.png', upload_to='images'),
        ),
    ]
