# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 17:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20170708_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'wma'])]),
        ),
    ]
