# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20170708_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, default='G:/website/static/creenshot_43.png', upload_to='images'),
        ),
    ]
