# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20170709_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
